# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47770be5d7142a3d464d7c5e82d05e709d27bc54b0405c852f0cc97b2a03dec72d4b2c12e88815bf05d2a8699e173a0c3a2f19374245db85f3366734aeebeae1

test:
  secret_key_base: 1a8baa2942600f78bc1970785e42eadbf3ccf37f9fbf2fa11cf0132df0690026ab3e8558bc4961484775279cf865e41d44395e68085efd717c9d0b034c9a3d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
